name: A workflow for my Hello Beta-World file
on: push

jobs:
  build:
    name: Hello beta-world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./action-a
        env:
          MY_NAME: "Casanova"